/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangProfileIndexRouteImport } from './routes/$lang/profile/index'
import { Route as LangDashboardIndexRouteImport } from './routes/$lang/dashboard/index'
import { Route as LangAuthIndexRouteImport } from './routes/$lang/auth/index'
import { Route as LangAdminIndexRouteImport } from './routes/$lang/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LangProfileSettingsRouteImport } from './routes/$lang/profile/settings'
import { Route as LangLegalTermsRouteImport } from './routes/$lang/legal/terms'
import { Route as LangLegalPrivacyRouteImport } from './routes/$lang/legal/privacy'
import { Route as LangLegalImprintRouteImport } from './routes/$lang/legal/imprint'
import { Route as LangDashboardTimerRouteImport } from './routes/$lang/dashboard/timer'
import { Route as LangDashboardGoalsRouteImport } from './routes/$lang/dashboard/goals'
import { Route as LangDashboardCalendarRouteImport } from './routes/$lang/dashboard/calendar'
import { Route as LangDashboardAchievementsRouteImport } from './routes/$lang/dashboard/achievements'
import { Route as LangAuthRegisterRouteImport } from './routes/$lang/auth/register'
import { Route as LangAuthPasswordResetRouteImport } from './routes/$lang/auth/password-reset'
import { Route as LangAuthLoginRouteImport } from './routes/$lang/auth/login'
import { Route as LangAuthForgotPasswordRouteImport } from './routes/$lang/auth/forgot-password'
import { Route as LangDashboardGoalsIndexRouteImport } from './routes/$lang/dashboard/goals/index'
import { Route as LangAdminUsersIndexRouteImport } from './routes/$lang/admin/users/index'
import { Route as LangDashboardGoalsGoalIdRouteImport } from './routes/$lang/dashboard/goals/$goalId'
import { Route as LangAdminUsersUserIdRouteImport } from './routes/$lang/admin/users/$userId'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangProfileIndexRoute = LangProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDashboardIndexRoute = LangDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthIndexRoute = LangAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAdminIndexRoute = LangAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LangRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangProfileSettingsRoute = LangProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangLegalTermsRoute = LangLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangLegalPrivacyRoute = LangLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangLegalImprintRoute = LangLegalImprintRouteImport.update({
  id: '/legal/imprint',
  path: '/legal/imprint',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDashboardTimerRoute = LangDashboardTimerRouteImport.update({
  id: '/dashboard/timer',
  path: '/dashboard/timer',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDashboardGoalsRoute = LangDashboardGoalsRouteImport.update({
  id: '/dashboard/goals',
  path: '/dashboard/goals',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDashboardCalendarRoute = LangDashboardCalendarRouteImport.update({
  id: '/dashboard/calendar',
  path: '/dashboard/calendar',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDashboardAchievementsRoute =
  LangDashboardAchievementsRouteImport.update({
    id: '/dashboard/achievements',
    path: '/dashboard/achievements',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangAuthRegisterRoute = LangAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthPasswordResetRoute = LangAuthPasswordResetRouteImport.update({
  id: '/auth/password-reset',
  path: '/auth/password-reset',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthLoginRoute = LangAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthForgotPasswordRoute = LangAuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDashboardGoalsIndexRoute = LangDashboardGoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangDashboardGoalsRoute,
} as any)
const LangAdminUsersIndexRoute = LangAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDashboardGoalsGoalIdRoute =
  LangDashboardGoalsGoalIdRouteImport.update({
    id: '/$goalId',
    path: '/$goalId',
    getParentRoute: () => LangDashboardGoalsRoute,
  } as any)
const LangAdminUsersUserIdRoute = LangAdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/auth/forgot-password': typeof LangAuthForgotPasswordRoute
  '/$lang/auth/login': typeof LangAuthLoginRoute
  '/$lang/auth/password-reset': typeof LangAuthPasswordResetRoute
  '/$lang/auth/register': typeof LangAuthRegisterRoute
  '/$lang/dashboard/achievements': typeof LangDashboardAchievementsRoute
  '/$lang/dashboard/calendar': typeof LangDashboardCalendarRoute
  '/$lang/dashboard/goals': typeof LangDashboardGoalsRouteWithChildren
  '/$lang/dashboard/timer': typeof LangDashboardTimerRoute
  '/$lang/legal/imprint': typeof LangLegalImprintRoute
  '/$lang/legal/privacy': typeof LangLegalPrivacyRoute
  '/$lang/legal/terms': typeof LangLegalTermsRoute
  '/$lang/profile/settings': typeof LangProfileSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/auth/': typeof LangAuthIndexRoute
  '/$lang/dashboard/': typeof LangDashboardIndexRoute
  '/$lang/profile/': typeof LangProfileIndexRoute
  '/$lang/admin/users/$userId': typeof LangAdminUsersUserIdRoute
  '/$lang/dashboard/goals/$goalId': typeof LangDashboardGoalsGoalIdRoute
  '/$lang/admin/users/': typeof LangAdminUsersIndexRoute
  '/$lang/dashboard/goals/': typeof LangDashboardGoalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/auth/forgot-password': typeof LangAuthForgotPasswordRoute
  '/$lang/auth/login': typeof LangAuthLoginRoute
  '/$lang/auth/password-reset': typeof LangAuthPasswordResetRoute
  '/$lang/auth/register': typeof LangAuthRegisterRoute
  '/$lang/dashboard/achievements': typeof LangDashboardAchievementsRoute
  '/$lang/dashboard/calendar': typeof LangDashboardCalendarRoute
  '/$lang/dashboard/timer': typeof LangDashboardTimerRoute
  '/$lang/legal/imprint': typeof LangLegalImprintRoute
  '/$lang/legal/privacy': typeof LangLegalPrivacyRoute
  '/$lang/legal/terms': typeof LangLegalTermsRoute
  '/$lang/profile/settings': typeof LangProfileSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/admin': typeof LangAdminIndexRoute
  '/$lang/auth': typeof LangAuthIndexRoute
  '/$lang/dashboard': typeof LangDashboardIndexRoute
  '/$lang/profile': typeof LangProfileIndexRoute
  '/$lang/admin/users/$userId': typeof LangAdminUsersUserIdRoute
  '/$lang/dashboard/goals/$goalId': typeof LangDashboardGoalsGoalIdRoute
  '/$lang/admin/users': typeof LangAdminUsersIndexRoute
  '/$lang/dashboard/goals': typeof LangDashboardGoalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/auth/forgot-password': typeof LangAuthForgotPasswordRoute
  '/$lang/auth/login': typeof LangAuthLoginRoute
  '/$lang/auth/password-reset': typeof LangAuthPasswordResetRoute
  '/$lang/auth/register': typeof LangAuthRegisterRoute
  '/$lang/dashboard/achievements': typeof LangDashboardAchievementsRoute
  '/$lang/dashboard/calendar': typeof LangDashboardCalendarRoute
  '/$lang/dashboard/goals': typeof LangDashboardGoalsRouteWithChildren
  '/$lang/dashboard/timer': typeof LangDashboardTimerRoute
  '/$lang/legal/imprint': typeof LangLegalImprintRoute
  '/$lang/legal/privacy': typeof LangLegalPrivacyRoute
  '/$lang/legal/terms': typeof LangLegalTermsRoute
  '/$lang/profile/settings': typeof LangProfileSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/auth/': typeof LangAuthIndexRoute
  '/$lang/dashboard/': typeof LangDashboardIndexRoute
  '/$lang/profile/': typeof LangProfileIndexRoute
  '/$lang/admin/users/$userId': typeof LangAdminUsersUserIdRoute
  '/$lang/dashboard/goals/$goalId': typeof LangDashboardGoalsGoalIdRoute
  '/$lang/admin/users/': typeof LangAdminUsersIndexRoute
  '/$lang/dashboard/goals/': typeof LangDashboardGoalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/'
    | '/$lang/auth/forgot-password'
    | '/$lang/auth/login'
    | '/$lang/auth/password-reset'
    | '/$lang/auth/register'
    | '/$lang/dashboard/achievements'
    | '/$lang/dashboard/calendar'
    | '/$lang/dashboard/goals'
    | '/$lang/dashboard/timer'
    | '/$lang/legal/imprint'
    | '/$lang/legal/privacy'
    | '/$lang/legal/terms'
    | '/$lang/profile/settings'
    | '/api/auth/$'
    | '/$lang/admin/'
    | '/$lang/auth/'
    | '/$lang/dashboard/'
    | '/$lang/profile/'
    | '/$lang/admin/users/$userId'
    | '/$lang/dashboard/goals/$goalId'
    | '/$lang/admin/users/'
    | '/$lang/dashboard/goals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang'
    | '/$lang/auth/forgot-password'
    | '/$lang/auth/login'
    | '/$lang/auth/password-reset'
    | '/$lang/auth/register'
    | '/$lang/dashboard/achievements'
    | '/$lang/dashboard/calendar'
    | '/$lang/dashboard/timer'
    | '/$lang/legal/imprint'
    | '/$lang/legal/privacy'
    | '/$lang/legal/terms'
    | '/$lang/profile/settings'
    | '/api/auth/$'
    | '/$lang/admin'
    | '/$lang/auth'
    | '/$lang/dashboard'
    | '/$lang/profile'
    | '/$lang/admin/users/$userId'
    | '/$lang/dashboard/goals/$goalId'
    | '/$lang/admin/users'
    | '/$lang/dashboard/goals'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/'
    | '/$lang/auth/forgot-password'
    | '/$lang/auth/login'
    | '/$lang/auth/password-reset'
    | '/$lang/auth/register'
    | '/$lang/dashboard/achievements'
    | '/$lang/dashboard/calendar'
    | '/$lang/dashboard/goals'
    | '/$lang/dashboard/timer'
    | '/$lang/legal/imprint'
    | '/$lang/legal/privacy'
    | '/$lang/legal/terms'
    | '/$lang/profile/settings'
    | '/api/auth/$'
    | '/$lang/admin/'
    | '/$lang/auth/'
    | '/$lang/dashboard/'
    | '/$lang/profile/'
    | '/$lang/admin/users/$userId'
    | '/$lang/dashboard/goals/$goalId'
    | '/$lang/admin/users/'
    | '/$lang/dashboard/goals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/profile/': {
      id: '/$lang/profile/'
      path: '/profile'
      fullPath: '/$lang/profile/'
      preLoaderRoute: typeof LangProfileIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/dashboard/': {
      id: '/$lang/dashboard/'
      path: '/dashboard'
      fullPath: '/$lang/dashboard/'
      preLoaderRoute: typeof LangDashboardIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/auth/': {
      id: '/$lang/auth/'
      path: '/auth'
      fullPath: '/$lang/auth/'
      preLoaderRoute: typeof LangAuthIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/admin/': {
      id: '/$lang/admin/'
      path: '/admin'
      fullPath: '/$lang/admin/'
      preLoaderRoute: typeof LangAdminIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/profile/settings': {
      id: '/$lang/profile/settings'
      path: '/profile/settings'
      fullPath: '/$lang/profile/settings'
      preLoaderRoute: typeof LangProfileSettingsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/legal/terms': {
      id: '/$lang/legal/terms'
      path: '/legal/terms'
      fullPath: '/$lang/legal/terms'
      preLoaderRoute: typeof LangLegalTermsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/legal/privacy': {
      id: '/$lang/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/$lang/legal/privacy'
      preLoaderRoute: typeof LangLegalPrivacyRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/legal/imprint': {
      id: '/$lang/legal/imprint'
      path: '/legal/imprint'
      fullPath: '/$lang/legal/imprint'
      preLoaderRoute: typeof LangLegalImprintRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/dashboard/timer': {
      id: '/$lang/dashboard/timer'
      path: '/dashboard/timer'
      fullPath: '/$lang/dashboard/timer'
      preLoaderRoute: typeof LangDashboardTimerRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/dashboard/goals': {
      id: '/$lang/dashboard/goals'
      path: '/dashboard/goals'
      fullPath: '/$lang/dashboard/goals'
      preLoaderRoute: typeof LangDashboardGoalsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/dashboard/calendar': {
      id: '/$lang/dashboard/calendar'
      path: '/dashboard/calendar'
      fullPath: '/$lang/dashboard/calendar'
      preLoaderRoute: typeof LangDashboardCalendarRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/dashboard/achievements': {
      id: '/$lang/dashboard/achievements'
      path: '/dashboard/achievements'
      fullPath: '/$lang/dashboard/achievements'
      preLoaderRoute: typeof LangDashboardAchievementsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/auth/register': {
      id: '/$lang/auth/register'
      path: '/auth/register'
      fullPath: '/$lang/auth/register'
      preLoaderRoute: typeof LangAuthRegisterRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/auth/password-reset': {
      id: '/$lang/auth/password-reset'
      path: '/auth/password-reset'
      fullPath: '/$lang/auth/password-reset'
      preLoaderRoute: typeof LangAuthPasswordResetRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/auth/login': {
      id: '/$lang/auth/login'
      path: '/auth/login'
      fullPath: '/$lang/auth/login'
      preLoaderRoute: typeof LangAuthLoginRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/auth/forgot-password': {
      id: '/$lang/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/$lang/auth/forgot-password'
      preLoaderRoute: typeof LangAuthForgotPasswordRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/dashboard/goals/': {
      id: '/$lang/dashboard/goals/'
      path: '/'
      fullPath: '/$lang/dashboard/goals/'
      preLoaderRoute: typeof LangDashboardGoalsIndexRouteImport
      parentRoute: typeof LangDashboardGoalsRoute
    }
    '/$lang/admin/users/': {
      id: '/$lang/admin/users/'
      path: '/admin/users'
      fullPath: '/$lang/admin/users/'
      preLoaderRoute: typeof LangAdminUsersIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/dashboard/goals/$goalId': {
      id: '/$lang/dashboard/goals/$goalId'
      path: '/$goalId'
      fullPath: '/$lang/dashboard/goals/$goalId'
      preLoaderRoute: typeof LangDashboardGoalsGoalIdRouteImport
      parentRoute: typeof LangDashboardGoalsRoute
    }
    '/$lang/admin/users/$userId': {
      id: '/$lang/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/$lang/admin/users/$userId'
      preLoaderRoute: typeof LangAdminUsersUserIdRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangDashboardGoalsRouteChildren {
  LangDashboardGoalsGoalIdRoute: typeof LangDashboardGoalsGoalIdRoute
  LangDashboardGoalsIndexRoute: typeof LangDashboardGoalsIndexRoute
}

const LangDashboardGoalsRouteChildren: LangDashboardGoalsRouteChildren = {
  LangDashboardGoalsGoalIdRoute: LangDashboardGoalsGoalIdRoute,
  LangDashboardGoalsIndexRoute: LangDashboardGoalsIndexRoute,
}

const LangDashboardGoalsRouteWithChildren =
  LangDashboardGoalsRoute._addFileChildren(LangDashboardGoalsRouteChildren)

interface LangRouteRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangIndexRoute: typeof LangIndexRoute
  LangAuthForgotPasswordRoute: typeof LangAuthForgotPasswordRoute
  LangAuthLoginRoute: typeof LangAuthLoginRoute
  LangAuthPasswordResetRoute: typeof LangAuthPasswordResetRoute
  LangAuthRegisterRoute: typeof LangAuthRegisterRoute
  LangDashboardAchievementsRoute: typeof LangDashboardAchievementsRoute
  LangDashboardCalendarRoute: typeof LangDashboardCalendarRoute
  LangDashboardGoalsRoute: typeof LangDashboardGoalsRouteWithChildren
  LangDashboardTimerRoute: typeof LangDashboardTimerRoute
  LangLegalImprintRoute: typeof LangLegalImprintRoute
  LangLegalPrivacyRoute: typeof LangLegalPrivacyRoute
  LangLegalTermsRoute: typeof LangLegalTermsRoute
  LangProfileSettingsRoute: typeof LangProfileSettingsRoute
  LangAdminIndexRoute: typeof LangAdminIndexRoute
  LangAuthIndexRoute: typeof LangAuthIndexRoute
  LangDashboardIndexRoute: typeof LangDashboardIndexRoute
  LangProfileIndexRoute: typeof LangProfileIndexRoute
  LangAdminUsersUserIdRoute: typeof LangAdminUsersUserIdRoute
  LangAdminUsersIndexRoute: typeof LangAdminUsersIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangIndexRoute: LangIndexRoute,
  LangAuthForgotPasswordRoute: LangAuthForgotPasswordRoute,
  LangAuthLoginRoute: LangAuthLoginRoute,
  LangAuthPasswordResetRoute: LangAuthPasswordResetRoute,
  LangAuthRegisterRoute: LangAuthRegisterRoute,
  LangDashboardAchievementsRoute: LangDashboardAchievementsRoute,
  LangDashboardCalendarRoute: LangDashboardCalendarRoute,
  LangDashboardGoalsRoute: LangDashboardGoalsRouteWithChildren,
  LangDashboardTimerRoute: LangDashboardTimerRoute,
  LangLegalImprintRoute: LangLegalImprintRoute,
  LangLegalPrivacyRoute: LangLegalPrivacyRoute,
  LangLegalTermsRoute: LangLegalTermsRoute,
  LangProfileSettingsRoute: LangProfileSettingsRoute,
  LangAdminIndexRoute: LangAdminIndexRoute,
  LangAuthIndexRoute: LangAuthIndexRoute,
  LangDashboardIndexRoute: LangDashboardIndexRoute,
  LangProfileIndexRoute: LangProfileIndexRoute,
  LangAdminUsersUserIdRoute: LangAdminUsersUserIdRoute,
  LangAdminUsersIndexRoute: LangAdminUsersIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
